apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u8s2h336p-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u8s2h336p-go 
  name: u8s2h336p-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u8s2h336p-go 
