apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u8s2h336p-go 
  janus-idp.io/tekton: u8s2h336p-go
  backstage.io/kubernetes-id: u8s2h336p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u8s2h336p-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  